version: 2

defaults: &defaults
  working_directory: ~/ui-guide
  docker:
    - image: thomashoneyman/purescript:0.0.2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v0.0-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - v0.0-npm-cache-{{ .Branch }}
            - v0.0-npm-cache

      - restore_cache:
          keys:
            - v0.0-bower-cache-{{ .Branch }}-{{ checksum "bower.json" }}
            - v0.0-bower-cache-{{ .Branch }}
            - v0.0-bower-cache

      - run:
          name: Install dependencies and compile base
          command: |
            npm install
            pulp build

      - run:
          name: Verify the project and all components build successfully
          command: npm run build-ui

      - save_cache:
          key: v0.0-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - save_cache:
          key: v0.0-bower-cache-{{ .Branch }}-{{ checksum "bower.json" }}

      # Persist generated JS into the workspace
      - persist_to_workspace:
          root: docs
          paths:
            - .

  docs:
    <<: *defaults
    steps:
      - checkout

      run:
        name: Prepare branches locally
        command: |
          git checkout gh-pages
          git checkout master

      run:
        name: Set up gh-pages in worktree for easy artifact copying
        command: |
          mkdir ../gh-pages
          git worktree add ../gh-pages gh-pages

      - attach_workspace:
          at: persisted

      - run:
          name: Build CSS
          command: |
            cp -r persisted/dist docs/dist
            npm run install-css
            npm run build-css

      # Enable building docs with read/write SSH key
      - add_ssh_keys:
          fingerprints:
						- "bf:0e:a0:9d:37:6e:40:34:3c:72:90:f5:c8:93:cd:a5"

			- run:
					name: Push files to gh-pages branch on GitHub
					command: |
						rm -rf ../gh-pages/dist
						mv docs/dist ../gh-pages/dist
						cd ../gh-pages  # Moves into gh-pages branch
						git commit --allow-empty -a -m "Build triggered by CircleCI"
						git push -u origin gh-pages

workflows:
	version: 2
	build:
		jobs:
			- test

			# On master branch, rebuild documentation site
			- docs:
					filters:
						branches:
							only: master

					requires:
						- test
